from knowledge_graph import build_knowledge_graph


def find_sensor_dependencies(graph):
    """
    Find which dataset receives data from BZ_SENSOR_001.
    """

    query = """
    PREFIX dt: <http://example.org/digital-twin/>
    PREFIX ex: <http://example.org/environment/>

    SELECT ?dataset
    WHERE {
        ex:BZ_SENSOR_001 dt:providesDataTo ?dataset .
    }
    """

    results = graph.query(query)

    print("\nQUERY 1: What dataset receives data from BZ_SENSOR_001?")
    print("=" * 60)

    for row in results:
        print(f"Dataset: {row.dataset}")


def find_model_dependencies(graph):
    """
    Find which model receives input from the environmental dataset.
    """

    query = """
    PREFIX dt: <http://example.org/digital-twin/>
    PREFIX ex: <http://example.org/environment/>

    SELECT ?model
    WHERE {
        ex:Bolzano_Environmental_Dataset dt:providesInputTo ?model .
    }
    """

    results = graph.query(query)

    print("\nQUERY 2: Which model depends on the environmental dataset?")
    print("=" * 60)

    for row in results:
        print(f"Model: {row.model}")


def find_model_output(graph):
    """
    Find what output is generated by the Air Quality Model.
    """

    query = """
    PREFIX dt: <http://example.org/digital-twin/>
    PREFIX ex: <http://example.org/environment/>

    SELECT ?output
    WHERE {
        ex:Air_Quality_Model dt:generates ?output .
    }
    """

    results = graph.query(query)

    print("\nQUERY 3: What does the Air Quality Model generate?")
    print("=" * 60)

    for row in results:
        print(f"Output: {row.output}")


if __name__ == "__main__":

    # Build the knowledge graph
    graph = build_knowledge_graph()

    print("\nSEMANTIC DIGITAL TWIN QUERIES")
    print("=" * 60)

    # Run competency questions
    find_sensor_dependencies(graph)
    find_model_dependencies(graph)
    find_model_output(graph)